src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <description>Id that is unique identifier in Lodging Catalog Master database</description>
        <label>Expedia Hotel Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market_Manager_Name__c</fullName>
        <description>Name for Market Manager (Account Owner) from PSG Salesforce</description>
        <inlineHelpText>This is the Account Owner from PSG Salesforce</inlineHelpText>
        <label>Market Manager Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard external contact</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

src/objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <formula>Account__r.Expedia_Hotel_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expedia Hotel Id</label>
        <type>Text</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ReContracting_Token__c</fullName>
        <description>Token used to authenticate user</description>
        <label>ReContracting Token</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Recontracting_Role__c</fullName>
        <description>Used to determine security role on MM Intake form</description>
        <label>Recontracting Role</label>
        <picklist>
            <picklistValues>
                <fullName>Market Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Token_Issued_Date__c</fullName>
        <description>Date the Re-Contracting token was issued</description>
        <label>Token Issued Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Token_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate that the user has received the authentication token via email and clicked on the link</description>
        <label>Token Verified</label>
        <type>Checkbox</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region account resides in</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Term__c.object
<CustomObject>
    <description>Commercial Terms for re-contracting</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Commercial Term Description</description>
        <inlineHelpText>Commercial Term Description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date that the commercial term is active</description>
        <inlineHelpText>Date that the commercial term is active</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sitesVFReContracting_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class sitesVFReContracting_Test {

    static testMethod void myUnitTest() {
        // create user
        PSG_User__c psgUser = new PSG_User__c();
        
        psgUser.Email__c = 'joeuser@test.com';
        psgUser.Name = 'Joe User';
        psgUser.Recontracting_Role__c = 'Market Manager';
        psgUser.ReContracting_Token__c = 'asdfasdfasd';
        psgUser.Token_Issued_Date__c = Date.today();
        psgUser.Token_Verified__c = true;
        
        insert psgUser;
        
        // create region
        Region__c region = new Region__c(Name='Italy');
        insert region;
        
        // create account
        Account myAccount = new Account();
        myAccount.Name = 'Test Account';
        myAccount.Region__c = region.Id;
        myAccount.Market_Manager_Name__c = psgUser.Name;
        myAccount.Expedia_Hotel_Id__c = '999999999999';
        myAccount.ETP_Eligible__c = true;
        
        insert myAccount;
        
        // create contact
        Contact myContact = new Contact();
        myContact.FirstName = 'Jill';
        myContact.LastName = 'User';
        myContact.AccountId = myAccount.Id;
        
        insert myContact; 
        
        // create terms
        Term__c myTerm = new Term__c();
        myTerm.Description__c = 'Contract Length (months)';
        myTerm.Start_Date__c = System.today();
        
        insert myTerm;
        
        // get recontracting token
        psgUser = PSGUserClass.findByEmail(psgUser.Email__c);
        System.assertNotEquals(psgUser.ReContracting_Token__c, null);
        Apexpages.currentPage().getParameters().put('mm', psgUser.Email__c);
        Apexpages.currentPage().getParameters().put('token', psgUser.ReContracting_Token__c);

        test.startTest();
        
        sitesVFReContracting controller = new sitesVFReContracting();
        controller.SupplierTrainingByMM = false;
        system.assertEquals(controller.PSGUser.ReContracting_Token__c, psgUser.ReContracting_Token__c);
        system.assertEquals(controller.psguser.name, psgUser.name);
        
        
        // get available accounts
        List<sitesVFReContracting.AccountWrapper> accounts = controller.AvailableAccounts;
        system.assertNotEquals(accounts.isEmpty(), true);
        
        // set the selected accounts
        for(sitesVFReContracting.AccountWrapper myAccountWrapper : accounts) {
        	myAccountWrapper.SelectedContactId = myContact.Id;
        	myAccountWrapper.updateSelectedAccounts();
        }
        
        // verify that accounts have been selected
        System.assertNotEquals(controller.SelectedAccounts.isEmpty(), true);
        
        // verify that terms exist
        System.assertNotEquals(controller.AvailableTerms.isEmpty(), true);
        for(sitesVFReContracting.TermWrapper term : controller.AvailableTerms) {
        	term.SelectedValue = '5';
        }
        
        controller.Submit();
        // verify that a contract was created
        List<GSOContract__c> contracts = [Select Id From GSOContract__c Where Account__c = : myAccount.Id];
        System.assertNotEquals(contracts.isEmpty(), true);
        
        // verify navigation
        controller.first();
        controller.next();
        controller.previous();
        controller.last();
        controller.goToStep1();
        controller.goToStep2();
        controller.goToStep3();
        System.assertEquals(controller.hasNext, false);
       	System.assertEquals( controller.hasPrevious, false);
        
        test.stopTest();
    }
}