src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <description>Id that is unique identifier in Lodging Catalog Master database</description>
        <label>Expedia Hotel Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Assignment_Group_Name__c.object
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Groups__c.object
<CustomObject>
    <description>Used to assign ownership of records users via Apex</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <referenceTo>Assignment_Group_Name__c</referenceTo>
        <relationshipName>Assignment_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002Yj6ZEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>AG-{0000}</displayFormat>
        <label>Assignment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group_Member_Language__c.object
<CustomObject>
    <fields>
        <fullName>Group_Member__c</fullName>
        <label>Group Member</label>
        <referenceTo>Assignment_Groups__c</referenceTo>
        <relationshipLabel>Group Member Languages</relationshipLabel>
        <relationshipName>Group_Member_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Group Member Languages</relationshipLabel>
        <relationshipName>Group_Member_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member Language</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Group Member Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Member Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GuestClass_Test.cls
@isTest
private class GuestClass_Test {
	
	static void setupTestData() {
	   List<Account> testAccounts = new List<Account> {
            new Account(Name = 'A1', PSG_Language__c = 'Spanish', Expedia_Hotel_Id__c = '1')
           ,new Account(Name = 'A2', PSG_Language__c = 'French', Expedia_Hotel_Id__c = '2')
           ,new Account(Name = 'A3', PSG_Language__c = 'German', Expedia_Hotel_Id__c = '3')
           ,new Account(Name = 'A4', PSG_Language__c = 'Tralfamadorian', Expedia_Hotel_Id__c = '4')
	   };
	   insert testAccounts;
	   
	   List<Language__c> testLanguages = new List<Language__c>{
	   	   new Language__c (Name = 'Spanish')
	   	  ,new Language__c (Name = 'English')
	   	  ,new Language__c (Name = 'French')
	   	  ,new Language__c (Name = 'German')
	   };
	   insert testLanguages;
	   
	   List<User> testUsers = new List<User>{
	   	   new User (UserName = 'TestTest')
	   };
	   insert testUsers;
	   
	   Assignment_Group_Name__c myAG = new Assignment_Group_Name__c(Name = 'Fallback');
	   insert myAG;
	   
	   List<Assignment_Groups__c> groupMembers = new List<Assignment_Groups__c>{
	   	   new Assignment_Groups__c (User__c = testUsers[0].Id, Group_Name__c = myAG.Id)
	   };
	   insert groupMembers;
	   
	   List<Group_Member_Language__c> groupMemberLanguages = new List<Group_Member_Language__c>{
	       new Group_Member_Language__c (Language__c = testLanguages[0].Id, Group_Member__c = groupMembers[0].Id)
	      ,new Group_Member_Language__c (Language__c = testLanguages[1].Id, Group_Member__c = groupMembers[0].Id)
	   };
	   insert groupMemberLanguages;
	}

    static testMethod void shouldAttachToExistingCase() {}
    static testMethod void shouldCreateNewCase() {}
    static testMethod void shouldNotAttachToInProgressCase() {}
    static testMethod void shouldAssignToLowerFallbackUser() {}
    static testMethod void shouldNotAssignToInactiveUser() {}
    static testMethod void shouldDefaultToEnglish() {}
    static testMethod void shouldWorkInBulk() {}
}