src/objects/Assignment_Group_Name__c.object
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Groups__c.object
<CustomObject>
    <description>Used to assign ownership of records users via Apex</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <referenceTo>Assignment_Group_Name__c</referenceTo>
        <relationshipName>Assignment_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Active__c</fullName>
        <formula>if(User__r.Assignment_Group_Active__c=True,
     IF( User__r.IsActive=True,&quot;True&quot;,&quot;False&quot;) ,
     &quot;False&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>True if &quot;Assignment Group Active&quot; and &quot;Active&quot; fields on the user record are checked.  If True the users is available for this and all Assignment Groups.</inlineHelpText>
        <label>User Active</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002Yj6ZEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>AG-{0000}</displayFormat>
        <label>Assignment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group_Member_Language__c.object
<CustomObject>
    <fields>
        <fullName>Group_Member__c</fullName>
        <label>Group Member</label>
        <referenceTo>Assignment_Groups__c</referenceTo>
        <relationshipLabel>Group Member Languages</relationshipLabel>
        <relationshipName>Group_Member_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Group Member Languages</relationshipLabel>
        <relationshipName>Group_Member_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member Language</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Group Member Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Member Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GroupMemberLanguageClass.cls
public with sharing class GroupMemberLanguageClass {
	
	public GroupMemberLanguageClass(string groupName){
		this.buildMaps(groupName);
	}
		
    public Map<String, List<User>> getLanguageToUsersMap(){
    	return this.languageToUsersMap;
    }
    
    public Map<Id, List<Language__c>> getUserIdToLanguagesMap(){
    	return this.userIdToLanguagesMap;
    }
    	
	public void buildMaps(string groupName){
		this.languageToUsersMap = new Map<String, List<User>>();
		this.userIdToLanguagesMap = new Map<Id, List<Language__c>>();
		for (Group_Member_Language__c myMemberLanguage : [SELECT Id
		                                                         ,Group_Member__r.User__c
		                                                         ,Group_Member__r.User__r.Id
		                                                         ,Group_Member__r.User__r.Name
		                                                         ,Language__r.Name
	                                                        FROM Group_Member_Language__c 
	                                                        WHERE Group_Member__r.Group_Name__r.Name = :groupName
	                                                          AND Group_Member__r.User_Active__c = 'True']){
            if (this.languageToUsersMap.containsKey(myMemberLanguage.Language__r.Name)){
            	this.languageToUsersMap.get(myMemberLanguage.Language__r.Name).add(myMemberLanguage.Group_Member__r.User__r);
            } else{
            	this.languageToUsersMap.put(myMemberLanguage.Language__r.Name, new List<User>{myMemberLanguage.Group_Member__r.User__r});
            }
            if (this.userIdToLanguagesMap.containsKey(myMemberLanguage.Group_Member__r.User__c)){
            	this.userIdToLanguagesMap.get(myMemberLanguage.Group_Member__r.User__c).add(myMemberLanguage.Language__r);
            } else{
            	this.userIdToLanguagesMap.put(myMemberLanguage.Group_Member__r.User__c, new List<Language__c> {myMemberLanguage.Language__r});
            }
    	}
	}
	private Map<String, List<User>> languageToUsersMap;
    private Map<Id, List<Language__c>> userIdToLanguagesMap;
	
	public class LanguageUserAssignment {
		public User myUser;
		public List<Language__c> userLanguages;
		public Integer numberOfActiveFallbacks;
		
		public LanguageUserAssignment(User myUser, GroupMemberLanguageClass groupMemberLanguageObj){
			this.myUser = myUser;
			this.userLanguages = groupMemberLanguageObj.getUserIdToLanguagesMap().get(myUser.Id);
			this.numberOfActiveFallbacks = 0;
		}
	}
}