src/objects/Case_Time__c.object
<CustomObject>
    <description>Information related to the time a Case is open and being worked. Will store relevant details such as Case Age, Time with Support, Time with Customer, Time in New Status, calculated not only in true time, but also Business Time, as defined on the Case.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Time</relationshipLabel>
        <relationshipName>Case_Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Handle_Time__c</fullName>
        <description>The first time the Case is in an AHT Status</description>
        <label>First Handle Time</label>
        <summarizedField>Time_Log__c.In_Effect_Until__c</summarizedField>
        <summaryFilterItems>
            <field>Time_Log__c.New_Case_Status_Included_in_AHT__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Time_Log__c.Case_Time__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Case Time</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Case Time Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseTimeClass_Test.cls
@isTest
private class CaseTimeClass_Test {

	static testMethod void shouldHaveCaseTime() {
		Case myCase = new Case (Subject = 'TestCase', Status = 'New');
		insert myCase;
		
		Case_Time__c myCaseTime = CaseTimeClass.findByCaseId(myCase.Id);
		system.assertNotEquals(myCaseTime, null);
	}
	static testMethod void shouldNotHaveMultipleCaseTimes(){
		Case myCase = new Case (Subject = 'TestCase', Status = 'New');
		insert myCase;
		
		try{
			Case_Time__c myCaseTime = new Case_Time__c(Case__c = myCase.Id);
			insert myCaseTime;
		} catch (DmlException e){
			system.assert(e.getMessage().contains('DUPLICATE_VALUE'));
		}
		
		List<Case_Time__c> myCaseTimes = [SELECT Id FROM Case_Time__c WHERE Case__c = :myCase.Id];
		system.assertEquals(myCaseTimes.size(), 1);
	}
	
	static testMethod void shouldHaveFirstHandleTime() {
		Case myCase = new Case (Subject = 'TestCase', Status = 'New');
		insert myCase;
        
		myCase.Status = 'In Progress';
		update myCase;
        
		Case_Time__c myCaseTime = CaseTimeClass.findByCaseId(myCase.Id);
		system.assertNotEquals(myCaseTime.First_Handle_Time__c, null);
    }
    
    static testMethod void shouldFailGracefully(){
		Case myCase = new Case (Subject = 'TestCase', Status = 'New');
		insert myCase;
		
		List<Case_Time__c> myCaseTimes = [SELECT Id FROM Case_Time__c WHERE Case__c = :myCase.Id];
		delete myCaseTimes;
		
		myCase.Status = 'In Progress';
		update myCase;
    }
}