src/objects/Case_Time__c.object
<CustomObject>
    <description>Information related to the time a Case is open and being worked. Will store relevant details such as Case Age, Time with Support, Time with Customer, Time in New Status, calculated not only in true time, but also Business Time, as defined on the Case.</description>
    <fields>
        <fullName>Case_Business_Hours_ID__c</fullName>
        <description>Used by Apex Class to determine the difference in business hours. Using the formula fields removes the need for a SOQL query.</description>
        <formula>Case__r.BusinessHoursId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Business Hours ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed__c</fullName>
        <formula>If(Case__r.IsClosed, &quot;TRUE&quot;, &quot;FALSE&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Closed?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <formula>TEXT(Case__r.Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Change__c</fullName>
        <label>Most Recent Change</label>
        <summarizedField>Time_Log__c.In_Effect_Until__c</summarizedField>
        <summaryForeignKey>Time_Log__c.Case_Time__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Case Time</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Case Time Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Log__c.object
<CustomObject>
    <fields>
        <fullName>Business_Time_in_Hours__c</fullName>
        <label>Business Time in Hours</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Business_Hours_ID__c</fullName>
        <description>Used by Apex Class to determine the difference in business hours. Using the formula fields removes the need for a SOQL query.</description>
        <formula>Case_Time__r.Case__r.BusinessHoursId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Business Hours ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Closed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Owner__c</fullName>
        <description>Can&apos;t use a lookup to User, as there will be Time Logs for Cases that are/were owned by a Queue.</description>
        <label>Case Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <description>The Status of the Case at the time of the Snapshot</description>
        <label>Case Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Time__c</fullName>
        <label>Case Time</label>
        <referenceTo>Case_Time__c</referenceTo>
        <relationshipName>Case_Status_Times</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>In_Effect_From__c</fullName>
        <label>In Effect From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>In_Effect_Until__c</fullName>
        <label>In Effect Until</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Included_in_SLA_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger looks up Custom Setting to determine if this is a Stop Status or not.</description>
        <label>Included in SLA Time?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Change__c</fullName>
        <formula>Case_Time__r.Most_Recent_Change__c</formula>
        <label>Most Recent Change</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_Case_Status__c</fullName>
        <label>New Case Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Bucket__c</fullName>
        <label>Time Bucket</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Time Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Time Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeLogClass.cls
public with sharing class TimeLogClass {

	// Called from After Update Case Trigger
	public void logCaseTime(List<Case> newCases, Map<Id, Case> oldCaseMap){
        List<Time_Log__c> newCaseLogs = new List<Time_Log__c>();
        
        for (Case myCase : newCases){
            Case myOldCase = oldCaseMap.get(myCase.Id);
            if (myCase.Status != myOldCase.Status || myCase.OwnerId != myOldCase.OwnerId){
                Time_Log__c myTimeLog = new Time_Log__c(Case_Owner__c = myOldCase.OwnerId
                                                       ,Case_Status__c = myOldCase.Status
                                                       ,New_Case_Status__c = myCase.Status
                                                       ,In_Effect_Until__c = myCase.LastModifiedDate
                                                       ,Case_Time__c = myCase.Case_Time__c);
               newCaseLogs.add(myTimeLog);
            }
        }
        insert newCaseLogs;
	}
	
	// Called from Before Insert on Time Log
	public static void beforeNewTimeLogs(List<Time_Log__c> newTimeLogs){
	    CaseTimeClass caseTimeObj = new CaseTimeClass();
        
        for (Time_Log__c myTimeLog : newTimeLogs){
        	myTimeLog.Time_Bucket__c = caseTimeObj.getStatusTimeBucket(myTimeLog.Case_Status__c, myTimeLog.Case_Closed__c);
        	myTimeLog.Included_In_SLA_Time__c = caseTimeObj.isStatusIncludedInSLATime(myTimeLog.Case_Status__c, myTimeLog.Case_Closed__c);            
            myTimeLog.In_Effect_From__c = myTimeLog.Most_Recent_Change__c == null ? myTimeLog.In_Effect_Until__c : myTimeLog.Most_Recent_Change__c;            
            myTimeLog.Business_Time_in_Hours__c = BusinessHours.diff(myTimeLog.Case_Business_Hours_ID__c, myTimeLog.In_Effect_From__c, myTimeLog.In_Effect_Until__c)/3600000.0;
        }
	}
	
	public static Time_Log__c createNewTimeLog(Case_Time__c myCaseTime, Case myCase){
		Time_Log__c myTimeLog = new Time_Log__c();
		//TODO: CREATE TIME LOG
		//TODO: MAKE SURE DEACTIVATED OLDUSERS DOESNT BREAK LOGGING
		
		return myTimeLog;
	}
	
	//TODO: UPDATE METHODS TO USE THIS
	private boolean caseNeedsToLogTime(Case myCase, Case myOldCase){
		if (myCase.Status != myOldCase.Status || myCase.OwnerId != myOldCase.OwnerId){
			return true;
		}
		return false;
	}
}