src/objects/Case_Team__c.object
<CustomObject>
    <description>Used to look up the case record type and team based on the incoming email address</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Developer_Name__c</fullName>
        <description>Developer name of the record type</description>
        <inlineHelpText>Developer name of the record type</inlineHelpText>
        <label>Record Type Developer Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CaseTeam</label>
    <nameField>
        <label>Case Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseTeams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseTransferController.cls
public class CaseTransferController{
	
	public Case myCase {get;set;}
	public Case newCase {get;set;}
	public CaseComment newCaseComment {get;set;}
	public String transferringToCaseTeam {get;set;}
	
	public CaseTransferController(ApexPages.StandardController stdController){       
        this.myCase = (Case)stdController.getRecord();
    }
    
    public PageReference transferCase(){    	
    	PageReference originalCasePage = new ApexPages.StandardController(myCase).View();
        originalCasePage.setRedirect(true);
        return originalCasePage;
    }
    
    public List<selectOption> getCaseTeams() {
        List<selectOption> options = new List<selectOption>();
        
        for (Case_Team__c myCaseTeam : [SELECT Id, Name, Record_Type_Developer_Name__c FROM Case_Team__c WHERE Active__c = true]) { 
            options.add(new selectOption(myCaseTeam.Name, myCaseTeam.Name)); 
        }
        return options;
    }
}