src/objects/Case_Time__c.object
<CustomObject>
    <description>Information related to the time a Case is open and being worked. Will store relevant details such as Case Age, Time with Support, Time with Customer, Time in New Status, calculated not only in true time, but also Business Time, as defined on the Case.</description>
    <fields>
        <fullName>Case_Business_Hours_ID__c</fullName>
        <description>Used by Apex Class to determine the difference in business hours. Using the formula fields removes the need for a SOQL query.</description>
        <formula>Case__r.BusinessHoursId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Business Hours ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed__c</fullName>
        <formula>If(Case__r.IsClosed, &quot;TRUE&quot;, &quot;FALSE&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Closed?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Created_Date__c</fullName>
        <formula>Case__r.CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <formula>TEXT(Case__r.Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Time</relationshipLabel>
        <relationshipName>Case_Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Time_Included_in_SLA_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the current Case Status is a Stop Status as defined by the Custom Setting. This affects whether the time is considered &quot;Time with Support&quot; or &quot;Time with Customer&quot;


if logged time changes, run is stop status method</description>
        <inlineHelpText>Will default to false for  &quot;Closed - Reply&quot;  as that is only included in SLA if the Case is reopened</inlineHelpText>
        <label>Current Time Included in SLA Time?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Handle_Time__c</fullName>
        <description>The first time the Case is in an AHT Status</description>
        <label>First Handle Time</label>
        <summarizedField>Time_Log__c.In_Effect_Until__c</summarizedField>
        <summaryFilterItems>
            <field>Time_Log__c.New_Case_Status_Included_in_AHT__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Time_Log__c.Case_Time__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Change__c</fullName>
        <label>Most Recent Change</label>
        <summarizedField>Time_Log__c.In_Effect_Until__c</summarizedField>
        <summaryForeignKey>Time_Log__c.Case_Time__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Unique Key</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Time</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Case Time Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Status_Time_Bucket__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>The list of Statuses that are considered as &quot;Internal Status&quot;. Related to the Case Age in Business Hours app, moving away from a Custom Object and using Custom Setting to leverage caching, and not worry about SOQL queries.</description>
    <fields>
        <fullName>Included_in_SLA_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If not on this list, defaults to included in SLA</inlineHelpText>
        <label>Included in SLA Time</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The exact, *Case Sensitive* Status</description>
        <inlineHelpText>The exact, *Case Sensitive* Status</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Status Time Bucket</label>
</CustomObject>

src/objects/Time_Log__c.object
<CustomObject>
    <fields>
        <fullName>Case_Business_Hours_ID__c</fullName>
        <description>Used by Apex Class to determine the difference in business hours. Using the formula fields removes the need for a SOQL query.</description>
        <formula>Case_Time__r.Case__r.BusinessHoursId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Business Hours ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Closed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <description>The Status of the Case at the time of the Snapshot</description>
        <label>Case Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Time__c</fullName>
        <label>Case Time</label>
        <referenceTo>Case_Time__c</referenceTo>
        <relationshipName>Case_Status_Times</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Included_in_SLA_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger looks up Custom Setting to determine if this is a Stop Status or not.</description>
        <label>Included in SLA Time?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Change__c</fullName>
        <formula>Case_Time__r.Most_Recent_Change__c</formula>
        <label>Most Recent Change</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Bucket__c</fullName>
        <label>Time Bucket</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Time Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Time Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseTimeClass.cls
public with sharing class CaseTimeClass {

	public static Case_Time__c findByCaseId (Id myCaseId){
		return [SELECT Id
					  ,First_Handle_Time__c 
				 FROM Case_Time__c 
			 	WHERE Case__c = :myCaseId];
	}
	
	// Called from Before Insert on Case
	public void createCaseTimesForNewCases(List<Case> newCases){
        List<Case_Time__c> newCaseTimes = new List<Case_Time__c>();
        for (Integer i=0; i < newCases.size(); i++){
            Case_Time__c myCaseTime = new Case_Time__c();
            newCaseTimes.add(myCaseTime);
        }
        insert newCaseTimes;
        
        for (Case myCase : newCases){
            myCase.Case_Time__c = newCaseTimes.remove(0).Id;        
        }
        // clean up incase there were any failures inserting Cases
        if (!newCaseTimes.isEmpty()) delete newCaseTimes;
	}
	
	// Called from After Insert on Case
	// Link the CaseTime record to the Case. Need the CaseID after Insert
	public void updateCaseTimeAfterInsert(List<Case> newCases){
        List<Case_Time__c> newCaseTimes = new List<Case_Time__c>();
        List<Time_Log__c> newCaseLogs = new List<Time_Log__c>();
        TimeLogClass TimeLogObj = new TimeLogClass();
        for (Case myCase : newCases){
            if (myCase.Case_Time__c != null){
                Case_Time__c myCaseTime = new Case_Time__c(Id=myCase.Case_Time__c);
                myCaseTime.Case__c = myCase.Id;
                newCaseTimes.add(myCaseTime);
                
                //immediately log, incase the case is created in progress or whatever
				Time_Log__c myTimeLog = TimeLogObj.createNewTimeLog(myCase, null);
				newCaseLogs.add(myTimeLog);
            }
        }
        update newCaseTimes;
        insert newCaseLogs;
	}
	
	// Before Insert & Before Update on CaseTime
	public void recalculateCaseTimes(List<Case_Time__c> newCaseTimes){		
		for (Case_Time__c myCaseTime : newCaseTimes){
			//recalculate myCaseTime.Current_Time_Included_in_SLA_Time__c
			if (myCaseTime.Case_Status__c != null && myCaseTime.Case_Closed__c != null){
				myCaseTime.Current_Time_Included_in_SLA_Time__c = this.isStatusIncludedInSLATime(myCaseTime.Case_Status__c, myCaseTime.Case_Closed__c);
			}
			//recalculate myCaseTime.Business_Hours_Earliest_SLA_Due_Date__c
			if (myCaseTime.SLA_in_Hours__c != null){
				Long businessTimeRemainingInSLA = (myCaseTime.SLA_in_Hours__c - myCaseTime.Logged_Business_Hours_Included_in_SLA__c).longValue() * 3600000L;
				DateTime statusChangeTime = myCaseTime.Most_Recent_Change__c;
				if (statusChangeTime == null) statusChangeTime = system.now();
				myCaseTime.Business_Hours_Earliest_SLA_Due_Date__c = BusinessHours.add(myCaseTime.Case_Business_Hours_ID__c,statusChangeTime, businessTimeRemainingInSLA); 
			}
			//recalculate myCaseTime.Logged_Business_Hours_Until_First_Handle__c
			if (myCaseTime.First_Handle_Time__c != null && myCaseTime.Logged_Business_Hours_Until_First_Handle__c == null){
				myCaseTime.Logged_Business_Hours_Until_First_Handle__c = BusinessHours.diff(myCaseTime.Case_Business_Hours_ID__c, myCaseTime.Case_Created_Date__c, myCaseTime.First_Handle_Time__c)/3600000.0;				
			}
			//set the Unique_Key__c
			if (myCaseTime.Case__c != null && myCaseTime.Unique_Key__c == null){
				myCaseTime.Unique_Key__c = myCaseTime.Case__c;
			}
		}
	}
	
	public Map<String, Status_Time_Bucket__c> getStatusToTimeMap(){
		if (statusToTimeMap == null){
			statusToTimeMap = new Map<String, Status_Time_Bucket__c>();
			for (Status_Time_Bucket__c statusTime : Status_Time_Bucket__c.getAll().values()){
            	statusToTimeMap.put(statusTime.Status__c,statusTime);
        	}	
		}
		return statusToTimeMap;
	}
	
	public string getStatusTimeBucket(string caseStatus, boolean caseClosed){
		if (caseClosed) return 'Closed';
		if (getStatusToTimeMap().containsKey(caseStatus)){
			return getStatusToTimeMap().get(caseStatus).Time_Bucket__c;
		}
		return 'Included in SLA';
	}
	
	public boolean isStatusIncludedInSLATime (string caseStatus, boolean caseClosed, boolean closingCase){
		if (closedReplyIncludedInSLA (caseStatus, closingCase)) return true;
		if (caseClosed) return false;
		if (getStatusToTimeMap().containsKey(caseStatus)){
			return getStatusToTimeMap().get(caseStatus).Included_in_SLA_Time__c;
		}
		return true;
	}
	
	public boolean isStatusIncludedInSLATime (string caseStatus, string caseClosed){
		//formula fields cant return boolean. trying to save uneccessary soql here
		if (caseClosed == 'TRUE') return false;
		return this.isStatusIncludedInSLATime(caseStatus, false, false);
	}
	
	private boolean closedReplyIncludedInSLA(string oldCaseStatus, boolean caseStillClosed){
		if (oldCaseStatus == 'Closed - Reply'){
			if (!caseStillClosed) return true;			
		}
		return false; 
	}
	
	private Map<String, Status_Time_Bucket__c> statusToTimeMap;
}