src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Connectivity_System__c</fullName>
        <label>Connectivity System</label>
        <referenceTo>Connectivity_System__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <picklist>
            <picklistValues>
                <fullName>EQC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Connection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Connectivity_System__c.object
<CustomObject>
    <label>Connectivity System</label>
    <nameField>
        <label>Connectivity System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectivity Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rollout_Step__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Connection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connection</label>
        <referenceTo>Connection__c</referenceTo>
        <relationshipName>Connectivity_Rollouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rollout_Step__c</fullName>
        <label>Rollout Step</label>
        <picklist>
            <picklistValues>
                <fullName>Enrollment Form Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Information Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Confirmation Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Acceptance I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Acceptance II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Trained</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Training_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Class</label>
        <referenceTo>Training_Class__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rollout Step</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Rollout Step Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rollout Steps</pluralLabel>
    <recordTypes>
        <fullName>Connectivity</fullName>
        <active>true</active>
        <label>Connectivity</label>
    </recordTypes>
    <recordTypes>
        <fullName>ETP</fullName>
        <active>true</active>
        <label>ETP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Class__c.object
<CustomObject>
    <description>Class is junction between Account and Training Sessions</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account signing up for training</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Training Classes</relationshipLabel>
        <relationshipName>Training_Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_of_Last_Status__c</fullName>
        <description>Date of last status update</description>
        <label>Date of Last Status</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_Session__c</fullName>
        <description>Date session will be held</description>
        <formula>Training_Session__r.Date_of_Session__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date of Session</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiative__c</fullName>
        <description>initiative class is for</description>
        <formula>TEXT(Training_Session__r.Initiative__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initiative</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Training session class is attending</description>
        <label>Training Session</label>
        <referenceTo>Training_Session__c</referenceTo>
        <relationshipLabel>Training Classes</relationshipLabel>
        <relationshipName>Training_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Status__c</fullName>
        <description>Custom roll up summary.  Will be set via apex to last entry in rollout step.</description>
        <label>Training Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Training Class</label>
    <nameField>
        <displayFormat>TC-{00000000}</displayFormat>
        <label>Training Class Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Session__c.object
<CustomObject>
    <description>Training sessions for new initiatives</description>
    <fields>
        <fullName>Date_of_Session__c</fullName>
        <description>date of training session</description>
        <inlineHelpText>Date training session will be held</inlineHelpText>
        <label>Date of Session</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiative__c</fullName>
        <description>Initiative training session is for</description>
        <label>Initiative</label>
        <picklist>
            <picklistValues>
                <fullName>ETP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Training Session</label>
    <nameField>
        <displayFormat>TS-{00000000}</displayFormat>
        <label>Training Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RolloutStepClass_Test.cls
@isTest
private class RolloutStepClass_Test {

  static testMethod void myUnitTest() {
    Map<String,RecordType> RecordTypesMap = Utilities.getRecordTypesMap('Rollout_Step__c',true);
    Account myAccount = new Account (Name='AccountTest');
    insert myAccount;
        
		Connectivity_System__c myConnectivitySystem = new Connectivity_System__c (Name = 'TestConnectivitySystem');
		insert myConnectivitySystem;
		
		Connection__c myConnection = new Connection__c (Account__c = myAccount.Id
													   ,Connectivity_System__c = myConnectivitySystem.Id
													   ,Type__c = 'Type'
													   ,Platform__c = 'Platform');
													   
		insert myConnection;
		
		Rollout_Step__c myFirstRolloutStep = new Rollout_Step__c (Connection__c = myConnection.Id
		                                                         ,Rollout_Step__c = 'TestStep1'
		                                                         ,RecordTypeId = RecordTypesMap.get('Connectivity').Id);
		insert myFirstRolloutStep;
		
		List<Rollout_Step__c> myRolloutSteps = RolloutStepClass.getRolloutStepsByConnectionId(myConnection.Id);
		Rollout_Step__c mySecondRolloutStep = new Rollout_Step__c (Connection__c = myConnection.Id
		                                                          ,Rollout_Step__c = 'TestStep2'
		                                                          ,RecordTypeId = RecordTypesMap.get('Connectivity').Id);
		myRolloutSteps.add(mySecondRolloutStep);
		
		RolloutStepClass.insertNewRolloutSteps(myRolloutSteps);		
		system.assertEquals(RolloutStepClass.getRolloutStepsByConnectionId(myConnection.Id).size(), 2);
		mySecondRolloutStep = RolloutStepClass.getRolloutStepById(mySecondRolloutStep.Id);		
    }
    
  static testmethod void testTraining() {
  	Map<String,RecordType> RecordTypesMap = Utilities.getRecordTypesMap('Rollout_Step__c',true);
  	
  	Account myAccount = new Account (Name='AccountTest');
    insert myAccount;
    
    Training_Session__c trainingSession = new Training_Session__c(Initiative__c = 'ETP'
                                                                 ,Date_of_Session__c = System.today());                                     
    insert trainingSession;
    
    Training_Class__c trainingClass = new Training_Class__c(Account__c = myAccount.Id
                                                           ,Training_Session__c = trainingSession.Id);
    insert trainingClass;
    
    Rollout_Step__c rolloutStep = new Rollout_Step__c(Completed_Date__c = DateTime.now()
                                                     ,Training_Class__c = trainingClass.Id
                                                     ,Rollout_Step__c = 'Pending Acceptance I'
                                                     ,RecordTypeId = RecordTypesMap.get('Training').Id);
                                                           
    insert rolloutStep;
    
    trainingClass = [SELECT Id
                           ,Training_Status__c
                           ,Date_of_Last_Status__c
                       FROM Training_Class__c
                      WHERE Id = :trainingClass.Id];
                      
    system.assertEquals(trainingClass.Training_Status__c, rolloutStep.Rollout_Step__c);
    system.assertEquals(trainingClass.Date_of_Last_Status__c, rolloutStep.Completed_Date__c);
  	
  }
}