src/objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sitesReContractingSubmissions.cls
public class sitesReContractingSubmissions {

	public List<GSOContract__c> contracts {get; set;}
	public GSOContract__c contract {get; set;}
	public Boolean completed {get; set;}

    public PSG_User__c PSGUser {
    	get {
    		if(PSGUser == null) {
		        String approver = Apexpages.currentPage().getParameters().get('MM');
		        PSGUser = PSGUserClass.findByEmail(approver);
    		}
    		return PSGUser;
    	}
    	set;
	}

	public sitesReContractingSubmissions() {
		if(PSGUser != null) {
			this.contracts = GSOContractClass.getActiveContractsByMM(this.PSGUser.Id);
		} 
		
		// check for contract id
		Id contractId = (Id)Apexpages.currentPage().getParameters().get('contractId');
		if(contractId != null) {
			this.contract = GSOContractClass.findById(contractId);
		}
		
		completed = false;
	}
	
    public PageReference VerifyAuthentication() {
        // User has not been authenticated redirect to the authentication page
        if(PSGUserClass.isAuthenticatedUser(PSGUser) == false) { 
            return Page.ReContractingAuthentication;
        }

        // User has been authenticated
        return null;
    }

	public PageReference Step1() {
    	PageReference p = Page.rcSubmissionsStep1;
    	p.setRedirect(true);
		p.getParameters().put('MM', PSGUser.Email__c);
		return p;
	}

	public PageReference cancel() {
		try {
			contract.Status__c = 'Cancelled';
			update contract;
			completed = true;
		}catch(Exception ex){
			Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.Error, ex.getMessage()));
		}
		
		return Apexpages.currentPage();
	}
	
}