src/objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VisualforceEmail.cls
public with sharing class VisualforceEmail {

    public Id Case_Id {get; set;}
    public string EmailBody{
    	get { return 'original';}
    	set;
	}
    public GSOContract__c getGSOContract(){
    	Case myCase = [SELECT Id, AccountID FROM Case WHERE Id = :Case_Id];
    	GSOContract__c myContract = [SELECT Id FROM GSOContract__c WHERE Account__c = :myCase.AccountID];
    	return myContract;
    }
    
    //public string getEmailBody(){
    //    return 'this is fomr the controller';
    //}

}