src/objects/Guest__c.object
<CustomObject>
    <description>Guest Object</description>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Guests</relationshipLabel>
        <relationshipName>Guests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expedia_Booking_ID__c</fullName>
        <label>Expedia Booking ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Market Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reassigned to Europe CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodated at Original Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reassigned to APAC CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Arrival</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Guest</label>
    <nameField>
        <label>Guest  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GuestMassUpdateExtension.cls
public with sharing class GuestMassUpdateExtension {
    
    public Map<Id, Guest__c> openGuests;
    public Map<Id, Guest__c> openGuestsOriginal;
    List<GuestWrapper> myGuestWrappers;
    public Guest__c guestTemplate;
    public boolean allSelected {get;set;}
    
    
    //Extension
    public GuestMassUpdateExtension (ApexPages.StandardSetController controller) {
        this.allSelected = false;
    }
    
    public List<Guest__c> getOpenGuests(){
        if (this.openGuests == null){
            this.openGuests =  new Map<Id, Guest__c> ([SELECT  Id
					                                   ,Name
					                                   ,Expedia_Booking_ID__c
					                                   ,Status__c
					                                   ,Arrival_Date__c 
					                              FROM Guest__c 
					                             WHERE Case__c = :ApexPages.currentPage().getParameters().get('Id')
					                               AND Closed__c = false
					                          ORDER BY Arrival_Date__c ASC]
            );
            this.openGuestsOriginal = this.openGuests.deepClone();
        } return this.openGuests.values();
    }
    
    public PageReference Save(){
    	List<Guest__c> guestsToBeUpdated = new List<Guest__c>();
    	for (GuestWrapper myGuestWrapper : myGuestWrappers){
    		if (myGuestWrapper.myGuest.Status__c != openGuestsOriginal.get(myGuestWrapper.myGuest.Id).Status__c){
    			guestsToBeUpdated.add(myGuestWrapper.myGuest);
    		}
    	}
    	update guestsToBeUpdated;
    	
    	return new ApexPages.StandardController(new Case(Id=ApexPages.currentPage().getParameters().get('Id'))).view();
    }
    
    public void selectAll(){
        if (this.allSelected){
            for (GuestWrapper myGuestWrapper : this.getGuestWrappers()){
                myGuestWrapper.isSelected = true;
            }
        } else {
            for (GuestWrapper myGuestWrapper : this.getGuestWrappers()){
                myGuestWrapper.isSelected = false;
            }
        }
    }
    
    public List<GuestWrapper> getGuestWrappers(){
        if (this.myGuestWrappers == null){
            this.myGuestWrappers = new List<GuestWrapper>();
            for (Guest__c myGuest : this.getOpenGuests()){
                GuestWrapper myGuestWrapper = new GuestWrapper(myGuest);
                myGuestWrappers.add(myGuestWrapper);
            }   
        } return this.myGuestWrappers;
    }
    
    public Guest__c getGuestTemplate(){
        //TODO: Get RecordTypeID via Utilities Method
        if (this.guestTemplate == null){
            this.guestTemplate = new Guest__c(RecordTypeId = '012c000000008AO');
        } return this.guestTemplate;    
    }
    
    public void updateAllGuests(){
        for (GuestWrapper myGuestWrapper : this.myGuestWrappers){
            if (myGuestWrapper.isSelected){
                myGuestWrapper.myGuest.Status__c = this.guestTemplate.Status__c;
            }
        }
    }
    
    public PageReference cancel(){
        return new ApexPages.StandardController(new Case(Id=ApexPages.currentPage().getParameters().get('Id'))).cancel();
    }
    
    public class GuestWrapper{
        public Guest__c myGuest{get;set;}
        public boolean isSelected{get;set;}
        
        public GuestWrapper(Guest__c myGuest){
            this.myGuest = myGuest;
            this.isSelected = false;
        }
        public GuestWrapper(){}
        
    }
}