src/objects/Guest__c.object
<CustomObject>
    <description>Guest Object</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Guests</relationshipLabel>
        <relationshipName>Guests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Guest</label>
    <nameField>
        <label>Guest  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GuestAccountExtension.cls
public with sharing class GuestAccountExtension {

    public Guest__c myGuest{get;set;}
    
    public GuestAccountExtension (ApexPages.StandardController stdController) {
           if (!Test.isRunningTest()) stdController.addFields(this.FIELDNAMES);
           this.myGuest = (Guest__c) stdController.getRecord();
    }
    
    private List<String> FIELDNAMES = new List<String>{'Case__r.Account.Name'
                                                       ,'Case__r.Account.Fallback_Notes__c'};
}