src/objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSG_User_Region__c.object
<CustomObject>
    <fields>
        <fullName>PSG_User__c</fullName>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>PSG User Regions</relationshipLabel>
        <relationshipName>PSG_User_Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>PSG User Regions</relationshipLabel>
        <relationshipName>PSG_User_Regions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PSG User Region</label>
    <nameField>
        <displayFormat>PUR-{00000000}</displayFormat>
        <label>PSG User Region Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG User Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region account resides in</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PSGUserRegionClass.cls
public with sharing class PSGUserRegionClass {
	
	public static List<PSG_User_Region__c> findByRegion(Id regionId) {
		String myFields = 'PSG_User__c, PSG_User__r.Email__c, Region__c, Region__r.Name';
		
		// build where clause
    	List<SoqlBuilder.Condition> conditions = new List<SoqlBuilder.Condition>();
    	conditions.add(new SoqlBuilder.Condition('Region__c', String.valueOf(regionId)));
		
		return findBy(myFields, conditions, null, null);
	}

	/////// Private Methods
    private static List<PSG_User_Region__c> findBy(String myFields, List<SoqlBuilder.Condition> conditions, String conditionLogic, String orderBy) {
		String objectName = PSG_User_Region__c.sObjectType.getDescribe().getName();
		return SoqlBuilder.ExecuteSelectQuery(myFields, objectName, conditions, conditionLogic, orderBy);
    }

}