src/objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if user is active is PSG Salesforce</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSG_User_Region__c.object
<CustomObject>
    <fields>
        <fullName>PSG_User__c</fullName>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>PSG User Regions</relationshipLabel>
        <relationshipName>PSG_User_Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>PSG User Regions</relationshipLabel>
        <relationshipName>PSG_User_Regions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PSG User Region</label>
    <nameField>
        <displayFormat>PUR-{00000000}</displayFormat>
        <label>PSG User Region Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG User Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region account resides in</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Region is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PSGUserRegionClass_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PSGUserRegionClass_Test {

    static testMethod void myUnitTest() {
        
        // create psg user
        PSG_User__c myPSGUser = new PSG_User__c(Name='PSG', Active__c=true, Email__c='psg@expedia.com');
        insert myPSGUser;
        
        // create region
        Region__c myRegion = new Region__c(Name='GSO Region');
        insert myRegion;
        
        // create psg user region
        PSG_User_Region__c myPSGUserRegion = new PSG_User_Region__c(PSG_User__c=myPSGUser.Id, Region__c=myRegion.Id);
        insert myPSGUserRegion;
        
        test.startTest();
        
        for(PSG_User_Region__c psgUserRegions : PSGUserRegionClass.findByRegion(myRegion.Id)) {
        	System.assertEquals(psgUserRegions.PSG_User__c, myPSGUser.Id);
        }
        
        test.stopTest();
    }
}